DROP TABLE IF EXISTS "Role" CASCADE;
DROP TABLE IF EXISTS "Competency" CASCADE;
DROP TABLE IF EXISTS "Employee" CASCADE;
DROP TABLE IF EXISTS "Interview" CASCADE;
DROP TABLE IF EXISTS "IPR" CASCADE;
DROP TABLE IF EXISTS "Review" CASCADE;
DROP TABLE IF EXISTS "Survey" CASCADE;
DROP TABLE IF EXISTS "Test" CASCADE;
DROP TABLE IF EXISTS "Testing" CASCADE;

